[build]
  command = "npm run build"
  functions = "dist/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
